In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\Data Analysis Project\IBM HR Analytics Employee Attrition\Data\raw\IBM HR Analytics Employee Attrition.csv")

In [3]:
# Display the First Few Records and Last Few Records

print(df.head(5).to_string())
print()
print(df.tail(5).to_string())

   Age Attrition     BusinessTravel  DailyRate              Department  DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  EnvironmentSatisfaction  Gender  HourlyRate  JobInvolvement  JobLevel                JobRole  JobSatisfaction MaritalStatus  MonthlyIncome  MonthlyRate  NumCompaniesWorked Over18 OverTime  PercentSalaryHike  PerformanceRating  RelationshipSatisfaction  StandardHours  StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
0   41       Yes      Travel_Rarely       1102                   Sales                 1          2  Life Sciences              1               1                        2  Female          94               3         2        Sales Executive                4        Single           5993        19479                   8      Y      Yes                 11                  3                         1             80                 0                  8                      0                1               6                   4                        0                     5
1   49        No  Travel_Frequently        279  Research & Development                 8          1  Life Sciences              1               2                        3    Male          61               2         2     Research Scientist                2       Married           5130        24907                   1      Y       No                 23                  4                         4             80                 1                 10                      3                3              10                   7                        1                     7
2   37       Yes      Travel_Rarely       1373  Research & Development                 2          2          Other              1               4                        4    Male          92               2         1  Laboratory Technician                3        Single           2090         2396                   6      Y      Yes                 15                  3                         2             80                 0                  7                      3                3               0                   0                        0                     0
3   33        No  Travel_Frequently       1392  Research & Development                 3          4  Life Sciences              1               5                        4  Female          56               3         1     Research Scientist                3       Married           2909        23159                   1      Y      Yes                 11                  3                         3             80                 0                  8                      3                3               8                   7                        3                     0
4   27        No      Travel_Rarely        591  Research & Development                 2          1        Medical              1               7                        1    Male          40               3         1  Laboratory Technician                2       Married           3468        16632                   9      Y       No                 12                  3                         4             80                 1                  6                      3                3               2                   2                        2                     2

      Age Attrition     BusinessTravel  DailyRate              Department  DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  EnvironmentSatisfaction Gender  HourlyRate  JobInvolvement  JobLevel                    JobRole  JobSatisfaction MaritalStatus  MonthlyIncome  MonthlyRate  NumCompaniesWorked Over18 OverTime  PercentSalaryHike  PerformanceRating  RelationshipSatisfaction  StandardHours  StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
1465   36        No  Travel_Frequently        884  Research & Development                23          2        Medical              1            2061                        3   Male          41               4         2      Laboratory Technician                4       Married           2571        12290                   4      Y       No                 17                  3                         3             80                 1                 17                      3                3               5                   2                        0                     3
1466   39        No      Travel_Rarely        613  Research & Development                 6          1        Medical              1            2062                        4   Male          42               2         3  Healthcare Representative                1       Married           9991        21457                   4      Y       No                 15                  3                         1             80                 1                  9                      5                3               7                   7                        1                     7
1467   27        No      Travel_Rarely        155  Research & Development                 4          3  Life Sciences              1            2064                        2   Male          87               4         2     Manufacturing Director                2       Married           6142         5174                   1      Y      Yes                 20                  4                         2             80                 1                  6                      0                3               6                   2                        0                     3
1468   49        No  Travel_Frequently       1023                   Sales                 2          3        Medical              1            2065                        4   Male          63               2         2            Sales Executive                2       Married           5390        13243                   2      Y       No                 14                  3                         4             80                 0                 17                      3                2               9                   6                        0                     8
1469   34        No      Travel_Rarely        628  Research & Development                 8          3        Medical              1            2068                        2   Male          82               4         2      Laboratory Technician                3       Married           4404        10228                   2      Y       No                 12                  3                         1             80                 0                  6                      3                4               4                   3                        1                     2

In [4]:
# Dataset Dimensions 

print(df.shape)

(1470, 35)

In [5]:
# View Column Names

print(df.columns.tolist())

['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

In [6]:
# Dataset Information

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB
None

In [7]:
# Summary Statistics

print(df.describe().to_string())
print()

# To summarize categorical columns

print(df.describe(include="object").to_string())

               Age    DailyRate  DistanceFromHome    Education  EmployeeCount  EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement     JobLevel  JobSatisfaction  MonthlyIncome   MonthlyRate  NumCompaniesWorked  PercentSalaryHike  PerformanceRating  RelationshipSatisfaction  StandardHours  StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0     1470.000000              1470.000000  1470.000000     1470.000000  1470.000000      1470.000000    1470.000000   1470.000000         1470.000000        1470.000000        1470.000000               1470.000000         1470.0       1470.000000        1470.000000            1470.000000      1470.000000     1470.000000         1470.000000              1470.000000           1470.000000
mean     36.923810   802.485714          9.192517     2.912925            1.0     1024.865306                 2.721769    65.891156        2.729932     2.063946         2.728571    6502.931293  14313.103401            2.693197          15.209524           3.153741                  2.712245           80.0          0.793878          11.279592               2.799320         2.761224        7.008163            4.229252                 2.187755              4.123129
std       9.135373   403.509100          8.106864     1.024165            0.0      602.024335                 1.093082    20.329428        0.711561     1.106940         1.102846    4707.956783   7117.786044            2.498009           3.659938           0.360824                  1.081209            0.0          0.852077           7.780782               1.289271         0.706476        6.126525            3.623137                 3.222430              3.568136
min      18.000000   102.000000          1.000000     1.000000            1.0        1.000000                 1.000000    30.000000        1.000000     1.000000         1.000000    1009.000000   2094.000000            0.000000          11.000000           3.000000                  1.000000           80.0          0.000000           0.000000               0.000000         1.000000        0.000000            0.000000                 0.000000              0.000000
25%      30.000000   465.000000          2.000000     2.000000            1.0      491.250000                 2.000000    48.000000        2.000000     1.000000         2.000000    2911.000000   8047.000000            1.000000          12.000000           3.000000                  2.000000           80.0          0.000000           6.000000               2.000000         2.000000        3.000000            2.000000                 0.000000              2.000000
50%      36.000000   802.000000          7.000000     3.000000            1.0     1020.500000                 3.000000    66.000000        3.000000     2.000000         3.000000    4919.000000  14235.500000            2.000000          14.000000           3.000000                  3.000000           80.0          1.000000          10.000000               3.000000         3.000000        5.000000            3.000000                 1.000000              3.000000
75%      43.000000  1157.000000         14.000000     4.000000            1.0     1555.750000                 4.000000    83.750000        3.000000     3.000000         4.000000    8379.000000  20461.500000            4.000000          18.000000           3.000000                  4.000000           80.0          1.000000          15.000000               3.000000         3.000000        9.000000            7.000000                 3.000000              7.000000
max      60.000000  1499.000000         29.000000     5.000000            1.0     2068.000000                 4.000000   100.000000        4.000000     5.000000         4.000000   19999.000000  26999.000000            9.000000          25.000000           4.000000                  4.000000           80.0          3.000000          40.000000               6.000000         4.000000       40.000000           18.000000                15.000000             17.000000

       Attrition BusinessTravel              Department EducationField Gender          JobRole MaritalStatus Over18 OverTime
count       1470           1470                    1470           1470   1470             1470          1470   1470     1470
unique         2              3                       3              6      2                9             3      1        2
top           No  Travel_Rarely  Research & Development  Life Sciences   Male  Sales Executive       Married      Y       No
freq        1233           1043                     961            606    882              326           673   1470     1054

C:\Users\athish\AppData\Local\Temp\ipykernel_17552\2028845092.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include="object").to_string())

In [8]:
# Before analysis, categorize each feature based on its data type and business meaning
# This helps determine appropriate analysis techniques and visualizations

# Numerical Features

numerical_columns = df.select_dtypes(include=["int64","float64"]).columns
print("Numbercal Columns: ")
print(numerical_columns.tolist())

Numbercal Columns:
['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

In [9]:
# Categorical Features

Categorical_columns = df.select_dtypes(include="object").columns
print("Categorical columns :")
print(Categorical_columns.tolist())

Categorical columns :
['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'Over18', 'OverTime']

C:\Users\athish\AppData\Local\Temp\ipykernel_17552\1179719718.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  Categorical_columns = df.select_dtypes(include="object").columns

In [10]:
# Check Missing Values

missing_values = df.isnull().sum()

missing_values_per = (missing_values/len(df)*100).round(2)

summary = (
    pd.DataFrame({
        "Missing Values": missing_values,
        "Missing Values Percentage": missing_values_per
    })
    .sort_values(by="Missing Values", ascending=False)
)

summary[summary["Missing Values"] > 0]

Empty DataFrame
Columns: [Missing Values, Missing Values Percentage]
Index: []

In [11]:
# Check Duplicate Records

duplicate_rows = df.duplicated().sum()

print(f"Duplicate Rows: {duplicate_rows}")

Duplicate Rows: 0

In [12]:
# Verify Employee IDs Are Unique

duplicate_employee_id = df['EmployeeNumber'].duplicated().sum()
print(f"Duplicate Employee IDs: {duplicate_employee_id}")

Duplicate Employee IDs: 0

In [13]:
# Unique Values in Each Column

unique_value = pd.DataFrame({
    "Coulmn": df.columns,
    "Unique Values":  df.nunique()
})
unique_value.sort_values("Unique Values")

                                            Coulmn  Unique Values
EmployeeCount                        EmployeeCount              1
Over18                                      Over18              1
StandardHours                        StandardHours              1
Attrition                                Attrition              2
OverTime                                  OverTime              2
PerformanceRating                PerformanceRating              2
Gender                                      Gender              2
BusinessTravel                      BusinessTravel              3
Department                              Department              3
MaritalStatus                        MaritalStatus              3
RelationshipSatisfaction  RelationshipSatisfaction              4
StockOptionLevel                  StockOptionLevel              4
JobSatisfaction                    JobSatisfaction              4
EnvironmentSatisfaction    EnvironmentSatisfaction              4
JobInvolvement                      JobInvolvement              4
WorkLifeBalance                    WorkLifeBalance              4
Education                                Education              5
JobLevel                                  JobLevel              5
EducationField                      EducationField              6
TrainingTimesLastYear        TrainingTimesLastYear              7
JobRole                                    JobRole              9
NumCompaniesWorked              NumCompaniesWorked             10
PercentSalaryHike                PercentSalaryHike             15
YearsSinceLastPromotion    YearsSinceLastPromotion             16
YearsWithCurrManager          YearsWithCurrManager             18
YearsInCurrentRole              YearsInCurrentRole             19
DistanceFromHome                  DistanceFromHome             29
YearsAtCompany                      YearsAtCompany             37
TotalWorkingYears                TotalWorkingYears             40
Age                                            Age             43
HourlyRate                              HourlyRate             71
DailyRate                                DailyRate            886
MonthlyIncome                        MonthlyIncome           1349
MonthlyRate                            MonthlyRate           1427
EmployeeNumber                      EmployeeNumber           1470

In [14]:
# Inspect Categorical Values
# Display Unique Values for Categorical Columns

categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    print("=" * 50)
    print(f"{column}")
    print(df[column].unique())
    print()

==================================================
Attrition
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

==================================================
BusinessTravel
<StringArray>
['Travel_Rarely', 'Travel_Frequently', 'Non-Travel']
Length: 3, dtype: str

==================================================
Department
<StringArray>
['Sales', 'Research & Development', 'Human Resources']
Length: 3, dtype: str

==================================================
EducationField
<StringArray>
[   'Life Sciences',            'Other',          'Medical',
        'Marketing', 'Technical Degree',  'Human Resources']
Length: 6, dtype: str

==================================================
Gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str

==================================================
JobRole
<StringArray>
[          'Sales Executive',        'Research Scientist',
     'Laboratory Technician',    'Manufacturing Director',
 'Healthcare Representative',                   'Manager',
      'Sales Representative',         'Research Director',
           'Human Resources']
Length: 9, dtype: str

==================================================
MaritalStatus
<StringArray>
['Single', 'Married', 'Divorced']
Length: 3, dtype: str

==================================================
Over18
<StringArray>
['Y']
Length: 1, dtype: str

==================================================
OverTime
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

C:\Users\athish\AppData\Local\Temp\ipykernel_17552\1696870635.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns

In [15]:
# Frequency Distribution of Categories
# Understanding how categories are distributed helps identify class imbalance and unexpected values.

for column in categorical_columns:
    print("=" * 60)
    print(f"{column}")
    print(df[column].value_counts())
    print()

============================================================
Attrition
Attrition
No     1233
Yes     237
Name: count, dtype: int64

============================================================
BusinessTravel
BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

============================================================
Department
Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

============================================================
EducationField
EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

============================================================
Gender
Gender
Male      882
Female    588
Name: count, dtype: int64

============================================================
JobRole
JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

============================================================
MaritalStatus
MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

============================================================
Over18
Over18
Y    1470
Name: count, dtype: int64

============================================================
OverTime
OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [16]:
# Validate Numeric Ranges
# # Check for Negative Values in Numeric Columns

numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns

for column in numerical_columns:
    negative_count = (df[column] < 0).sum()

    if negative_count > 0 :
        print(f"{column}: {negative_count} Negative Values")

In [17]:
# Create a Data Quality Summary Table

Data_Quality_Summary = pd.DataFrame({
    "Metric" : [
        "Total Rows",
        "Total Columns",
        "Missing Values",
        "Duplicate Rows",
        "Duplicate Employee IDs",
        "Constant Columns" 
    ],
    "Results" : [
        len(df),
        len(df.columns),
        int(df.isnull().sum().sum()),
        int(df.duplicated().sum()),
        int(df['EmployeeNumber'].duplicated().sum()),
        (df.nunique() == 1).sum()
    ]
})

print(Data_Quality_Summary)

                   Metric  Results
0              Total Rows     1470
1           Total Columns       35
2          Missing Values        0
3          Duplicate Rows        0
4  Duplicate Employee IDs        0
5        Constant Columns        3

In [18]:
# ==========================================================
# Create a Working Copy of the Dataset
# ==========================================================

# Create a deep copy of the original DataFrame

df_clean = df.copy()

print(f"Original Dataset : {df.shape}")
print(f"Copied Dataset : {df_clean.shape}")

Original Dataset : (1470, 35)
Copied Dataset : (1470, 35)

In [19]:
# ==========================================================
# Data Cleaning & Preparation
# ==========================================================


# Identify Constant Columns

Constant_Column = df_clean.columns[df_clean.nunique() == 1].tolist()
print("Constant Columns : ")
print(Constant_Column)
print()

Constant Columns :
['EmployeeCount', 'Over18', 'StandardHours']

In [20]:
# Remove Constant Columns

df_clean.drop(columns= Constant_Column, inplace=True)
print(df_clean.shape)

(1470, 32)

In [21]:
remaining_constant_columns = df_clean.columns[df_clean.nunique() == 1].tolist()

print("Remaining Constant Columns:")
print(remaining_constant_columns)

Remaining Constant Columns:
[]

In [22]:
# Check whether EmployeeNumber exists
print('EmployeeNumber' in df_clean.columns)

True

In [23]:
# Remove EmployeeNumber

df_clean.drop(columns='EmployeeNumber', inplace=True)
print("Updated Shape:", df_clean.shape)

Updated Shape: (1470, 31)

In [24]:
# Verify and Optimize Data Types
# Now that we've cleaned unnecessary columns, we need to ensure each column has the correct data type.

print(df_clean.info())

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EnvironmentSatisfaction   1470 non-null   int64
 9   Gender                    1470 non-null   str
 10  HourlyRate                1470 non-null   int64
 11  JobInvolvement            1470 non-null   int64
 12  JobLevel                  1470 non-null   int64
 13  JobRole                   1470 non-null   str
 14  JobSatisfaction           1470 non-null   int64
 15  MaritalStatus             1470 non-null   str
 16  MonthlyIncome             1470 non-null   int64
 17  MonthlyRate               1470 non-null   int64
 18  NumCompaniesWorked        1470 non-null   int64
 19  OverTime                  1470 non-null   str
 20  PercentSalaryHike         1470 non-null   int64
 21  PerformanceRating         1470 non-null   int64
 22  RelationshipSatisfaction  1470 non-null   int64
 23  StockOptionLevel          1470 non-null   int64
 24  TotalWorkingYears         1470 non-null   int64
 25  TrainingTimesLastYear     1470 non-null   int64
 26  WorkLifeBalance           1470 non-null   int64
 27  YearsAtCompany            1470 non-null   int64
 28  YearsInCurrentRole        1470 non-null   int64
 29  YearsSinceLastPromotion   1470 non-null   int64
 30  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(23), str(8)
memory usage: 356.1 KB
None

In [25]:
# Count Each Data Type

print(df_clean.dtypes.value_counts())
df_clean.select_dtypes(include="object").columns.tolist()

int64    23
str       8
Name: count, dtype: int64

C:\Users\athish\AppData\Local\Temp\ipykernel_17552\3990832519.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_clean.select_dtypes(include="object").columns.tolist()

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'OverTime']

In [26]:
# Converting object datatype into category datatype

object_columns = df_clean.select_dtypes(include="object").columns
df_clean[object_columns] = df_clean[object_columns].astype("category")

C:\Users\athish\AppData\Local\Temp\ipykernel_17552\1612737977.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_columns = df_clean.select_dtypes(include="object").columns

In [27]:
# Verify the result

print(df_clean.dtypes.value_counts())
len(df_clean.select_dtypes(include="category").columns)

int64       23
category     2
category     1
category     1
category     1
category     1
category     1
category     1
Name: count, dtype: int64

8

In [28]:
# Final Dataset Validation

print("Shape :", df_clean.shape)

print("\nMissing Values:")
print(df_clean.isnull().sum().sum())

print("\nDuplicate Rows:")
print(df_clean.duplicated().sum())

print("\nRemaining Constant Columns:")
print(df_clean.columns[df_clean.nunique()==1].tolist())

Shape : (1470, 31)

Missing Values:
0

Duplicate Rows:
0

Remaining Constant Columns:
[]

In [ ]:
# ==========================================================
# Save the Cleaned Dataset
# ==========================================================


df_clean.to_csv("IBM_HR_Analytics_Cleaned.csv", index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!